// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {hottrend} from '../models';
import {tools} from '../models';
import {mcp} from '../models';
import {main} from '../models';

export function AddAgentConfig(arg1:models.AgentConfig):Promise<string>;

export function AddMCPServer(arg1:models.MCPServerConfig):Promise<string>;

export function AddToWatchlist(arg1:models.Stock):Promise<string>;

export function CancelMeeting(arg1:string):Promise<boolean>;

export function CheckForUpdate():Promise<services.UpdateInfo>;

export function ClearSessionMessages(arg1:string):Promise<string>;

export function DeleteAgentConfig(arg1:string):Promise<string>;

export function DeleteMCPServer(arg1:string):Promise<string>;

export function DoUpdate():Promise<string>;

export function GetAgentConfigs():Promise<Array<models.AgentConfig>>;

export function GetAllHotTrends():Promise<Array<hottrend.HotTrendResult>>;

export function GetAvailableTools():Promise<Array<tools.ToolInfo>>;

export function GetConfig():Promise<models.AppConfig>;

export function GetCurrentVersion():Promise<string>;

export function GetHotTrend(arg1:string):Promise<hottrend.HotTrendResult>;

export function GetHotTrendPlatforms():Promise<Array<hottrend.PlatformInfo>>;

export function GetKLineData(arg1:string,arg2:string,arg3:number):Promise<Array<models.KLineData>>;

export function GetLongHuBangDetail(arg1:string,arg2:string):Promise<Array<models.LongHuBangDetail>>;

export function GetLongHuBangList(arg1:number,arg2:number,arg3:string):Promise<services.LongHuBangListResult>;

export function GetMCPServerTools(arg1:string):Promise<Array<mcp.ToolInfo>>;

export function GetMCPServers():Promise<Array<models.MCPServerConfig>>;

export function GetMCPStatus():Promise<Array<mcp.ServerStatus>>;

export function GetOrCreateSession(arg1:string,arg2:string):Promise<models.StockSession>;

export function GetOrderBook(arg1:string):Promise<models.OrderBook>;

export function GetSessionMessages(arg1:string):Promise<Array<models.ChatMessage>>;

export function GetStockRealTimeData(arg1:Array<string>):Promise<Array<models.Stock>>;

export function GetTelegraphList():Promise<Array<services.Telegraph>>;

export function GetWatchlist():Promise<Array<models.Stock>>;

export function Greet(arg1:string):Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function RemoveFromWatchlist(arg1:string):Promise<string>;

export function RestartApp():Promise<string>;

export function SearchStocks(arg1:string):Promise<Array<services.StockSearchResult>>;

export function SendMeetingMessage(arg1:main.MeetingMessageRequest):Promise<Array<models.ChatMessage>>;

export function TestMCPConnection(arg1:string):Promise<mcp.ServerStatus>;

export function UpdateAgentConfig(arg1:models.AgentConfig):Promise<string>;

export function UpdateConfig(arg1:models.AppConfig):Promise<string>;

export function UpdateMCPServer(arg1:models.MCPServerConfig):Promise<string>;

export function UpdateStockPosition(arg1:string,arg2:number,arg3:number):Promise<string>;

export function WindowClose():Promise<void>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;
