// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAgentConfig(arg1) {
  return window['go']['main']['App']['AddAgentConfig'](arg1);
}

export function AddMCPServer(arg1) {
  return window['go']['main']['App']['AddMCPServer'](arg1);
}

export function AddToWatchlist(arg1) {
  return window['go']['main']['App']['AddToWatchlist'](arg1);
}

export function CancelMeeting(arg1) {
  return window['go']['main']['App']['CancelMeeting'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearSessionMessages(arg1) {
  return window['go']['main']['App']['ClearSessionMessages'](arg1);
}

export function DeleteAgentConfig(arg1) {
  return window['go']['main']['App']['DeleteAgentConfig'](arg1);
}

export function DeleteMCPServer(arg1) {
  return window['go']['main']['App']['DeleteMCPServer'](arg1);
}

export function DoUpdate() {
  return window['go']['main']['App']['DoUpdate']();
}

export function GetAgentConfigs() {
  return window['go']['main']['App']['GetAgentConfigs']();
}

export function GetAllHotTrends() {
  return window['go']['main']['App']['GetAllHotTrends']();
}

export function GetAvailableTools() {
  return window['go']['main']['App']['GetAvailableTools']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetHotTrend(arg1) {
  return window['go']['main']['App']['GetHotTrend'](arg1);
}

export function GetHotTrendPlatforms() {
  return window['go']['main']['App']['GetHotTrendPlatforms']();
}

export function GetKLineData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetKLineData'](arg1, arg2, arg3);
}

export function GetLongHuBangDetail(arg1, arg2) {
  return window['go']['main']['App']['GetLongHuBangDetail'](arg1, arg2);
}

export function GetLongHuBangList(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLongHuBangList'](arg1, arg2, arg3);
}

export function GetMCPServerTools(arg1) {
  return window['go']['main']['App']['GetMCPServerTools'](arg1);
}

export function GetMCPServers() {
  return window['go']['main']['App']['GetMCPServers']();
}

export function GetMCPStatus() {
  return window['go']['main']['App']['GetMCPStatus']();
}

export function GetOrCreateSession(arg1, arg2) {
  return window['go']['main']['App']['GetOrCreateSession'](arg1, arg2);
}

export function GetOrderBook(arg1) {
  return window['go']['main']['App']['GetOrderBook'](arg1);
}

export function GetSessionMessages(arg1) {
  return window['go']['main']['App']['GetSessionMessages'](arg1);
}

export function GetStockRealTimeData(arg1) {
  return window['go']['main']['App']['GetStockRealTimeData'](arg1);
}

export function GetTelegraphList() {
  return window['go']['main']['App']['GetTelegraphList']();
}

export function GetWatchlist() {
  return window['go']['main']['App']['GetWatchlist']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RemoveFromWatchlist(arg1) {
  return window['go']['main']['App']['RemoveFromWatchlist'](arg1);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SearchStocks(arg1) {
  return window['go']['main']['App']['SearchStocks'](arg1);
}

export function SendMeetingMessage(arg1) {
  return window['go']['main']['App']['SendMeetingMessage'](arg1);
}

export function TestMCPConnection(arg1) {
  return window['go']['main']['App']['TestMCPConnection'](arg1);
}

export function UpdateAgentConfig(arg1) {
  return window['go']['main']['App']['UpdateAgentConfig'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateMCPServer(arg1) {
  return window['go']['main']['App']['UpdateMCPServer'](arg1);
}

export function UpdateStockPosition(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateStockPosition'](arg1, arg2, arg3);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}
